<?xml version="1.0"?>
<package format="3">
  <name>gps_localization</name>
  <version>0.0.0</version>
  <description>The localization package</description>

  <maintainer email="17698246@qq.com">wei</maintainer>
  <license>WTFPL</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>localization_msgs</depend>
  <depend>Boost</depend>
  <depend>OpenCV</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
