float64 v_veh_pos_yreqdou
float64 v_veh_pos_xreqdou
float64 rt3_width_rel
uint8 mc_mode
## Left object1
float64 rt3_v_long_obj
float64 rt3_l_long_obj
float64 rt3_v_lat_obj
float64 rt3_l_lat_obj
float64 rt3_a_long_obj
float64 rt3_a_lat_obj
float64 rt3_width
uint8 rt3_track_id
uint8 rt3_object_class

## Left object2
float64 rt5_v_long_obj
float64 rt5_l_long_obj
float64 rt5_v_lat_obj
float64 rt5_l_lat_obj
float64 rt5_a_long_obj
float64 rt5_a_lat_obj
float64 rt5_width
uint8 rt5_track_id
uint8 rt5_object_class

## front object1
float64 rt1_v_long_obj
float64 rt1_l_long_obj
float64 rt1_v_lat_obj
float64 rt1_l_lat_obj
float64 rt1_a_long_obj
float64 rt1_a_lat_obj
float64 rt1_width
uint8 rt1_track_id
uint8 rt1_object_class

## front object2
float64 rt2_v_long_obj
float64 rt2_l_long_obj
float64 rt2_v_lat_obj
float64 rt2_l_lat_obj
float64 rt2_a_long_obj
float64 rt2_a_lat_obj
float64 rt2_width
uint8 rt2_track_id
uint8 rt2_object_class



## right object1
float64 rt4_v_long_obj
float64 rt4_l_long_obj
float64 rt4_v_lat_obj
float64 rt4_l_lat_obj
float64 rt4_a_long_obj
float64 rt4_a_lat_obj
float64 rt4_width
uint8 rt4_track_id
uint8 rt4_object_class

## right object2
float64 rt6_v_long_obj
float64 rt6_l_long_obj
float64 rt6_v_lat_obj
float64 rt6_l_lat_obj
float64 rt6_a_long_obj
float64 rt6_a_lat_obj
float64 rt6_width
uint8 rt6_track_id
uint8 rt6_object_class

## front object1
float64 rts1_v_long_obj
float64 rts1_l_long_obj
float64 rts1_v_lat_obj
float64 rts1_l_lat_obj
float64 rts1_a_long_obj
float64 rts1_a_lat_obj
float64 rts1_width
uint8 rts1_track_id
uint8 rts1_object_class

## front object2
float64 rts2_v_long_obj
float64 rts2_l_long_obj
float64 rts2_v_lat_obj
float64 rts2_l_lat_obj
float64 rts2_a_long_obj
float64 rts2_a_lat_obj
float64 rts2_width
uint8 rts2_track_id
uint8 rts2_object_class

## Left object1
float64 rts3_v_long_obj
float64 rts3_l_long_obj
float64 rts3_v_lat_obj
float64 rts3_l_lat_obj
float64 rts3_a_long_obj
float64 rts3_a_lat_obj
float64 rts3_width
uint8 rts3_track_id
uint8 rts3_object_class

## right object2
float64 rts4_v_long_obj
float64 rts4_l_long_obj
float64 rts4_v_lat_obj
float64 rts4_l_lat_obj
float64 rts4_a_long_obj
float64 rts4_a_lat_obj
float64 rts4_width
uint8 rts4_track_id
uint8 rts4_object_class

##Lane Type
uint8 lane_left_type
##Lane Marker Type,Left Lane Marking
# 0-->None;
# 1-->Solid
# 2-->Dashed
# 3-->Reserved
# 4-->Botts Dots
# 5-->Reserved
# 6-->Invailid
# 7-->Undecided
# 8-->Double lane Marker
## end
uint8 lane_right_type
##Lane Marker Type,Right Lane Marking
# 0-->None;
# 1-->Solid
# 2-->Dashed
# 3-->Reserved
# 4-->Botts Dots
# 5-->Reserved
# 6-->Invailid
# 7-->Undecided
# 8-->Double lane Marker
## end
uint8 lane_right_neig_type
##Lane Marker Type,Right Neighbor Lane Marking
# 0-->None;
# 1-->Solid
# 2-->Dashed
# 3-->Reserved
# 4-->Botts Dots
# 5-->Reserved
# 6-->Invailid
# 7-->Undecided
# 8-->Double lane Marker
## end
uint8 lane_left_neig_type
##Lane Marker Type,Left Neighbor Lane Marking
# 0-->None;
# 1-->Solid
# 2-->Dashed
# 3-->Reserved
# 4-->Botts Dots
# 5-->Reserved
# 6-->Invailid
# 7-->Undecided
# 8-->Double lane Marker
## end
uint8 lane_right_neig_col
## Lane Marker Color,Right Neighbor Lane Marking
# 0-->Unknown
# 1-->Yellow
# 2-->White
# 3-->Blue
##end
float32 lane_right_neig_a0
uint8 lane_left_neig_col
## Lane Marker Color,Left Neighbor Lane Marking
# 0-->Unknown
# 1-->Yellow
# 2-->White
# 3-->Blue
##end
float32 lane_left_neig_a0
uint8 lane_right_indv_col
## Lane Marker Color,Right Lane Marking
# 0-->Unknown
# 1-->Yellow
# 2-->White
# 3-->Blue
##end
float32 lane_right_indv_a0
uint8 lane_left_indv_col
## Lane Marker Color,Left Lane Marking
# 0-->Unknown
# 1-->Yellow
# 2-->White
# 3-->Blue
##end
float32 lane_left_indv_a0
float32 o_traiedel_x
float32 o_traiedel_y
float32 o_traie_num_aim
float32 heading_delta_angle
float32 vehicle_heading

float32 vehicle_x
float32 vehicle_y

float32 v_obj_pointx1                   
float32 v_obj_pointx2   
float32 v_obj_pointy1
float32 v_obj_pointy2