SingleObj[] front
SingleObj[] left
SingleObj[] right
SingleObj[] left_front
SingleObj[] right_front
SingleObj[] back

# eight point order

#  ground
#    5     6     
#    1     2
#      car
#  no ground
#    7     8     
#    3     4
#      car 
#float64[] Left_left_down_min
#float64[] Left_right_down_min
#float64[] Left_left_up_min
#float64[] Left_right_up_min
#float64[] Left_left_down_max
#float64[] Left_right_down_max
#float64[] Left_left_up_max
#float64[] Left_right_up_max
